---
version: "3"

services:
  pocketbase:
    image: kdpuvvadi/pocketbase:latest
    container_name: pocketbase
    volumes:
      # use either volumes of bind mounts to store the data
      # - pocketbase:/usr/src/app/pb_data
      - ./pb_data:/usr/src/app/pb_data
    ports:
      - 8090:8090
    restart: unless-stopped

# uncomment this to use volume
# volumes:
#   pocketbase:
