# fly.toml app configuration file generated for stations on 2023-11-09T17:14:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stations"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
