name: Deploy to gitea

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKER_FILE: Dockerfile
      VERSION: '0.25.7'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y binfmt-support
          curl -L -o /tmp/qemu.sh 'https://raw.githubusercontent.com/qemu/qemu/master/scripts/qemu-binfmt-conf.sh'
          chmod +x /tmp/qemu.sh
          sudo /tmp/qemu.sh --debian

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Log into gitea
        uses: docker/login-action@v3.1.0
        with:
          registry: git.local.puvvadi.net
          username: ${{ secrets.GITEA_USER }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Build and push to registry
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            git.local.puvvadi.net/kd/pocketbase:${{ env.VERSION }}
            git.local.puvvadi.net/kd/pocketbase:latest
          cache-from: type=registry,ref=${{ github.repository	}}:latest
          cache-to: type=inline
